name: nodejs-16-test

on:
  workflow_call:
jobs:
  test:
    runs-on: ubuntu-latest    
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: "Initializing repository"
      uses: actions/checkout@v3
    - name: "Setting up node"
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: "Installing npm packages"
      run: npm install
    - name: "Running tests"
      run: npm run test
    