name: Node.js CI

on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: "[Default] Repo initialization"
      uses: actions/checkout@v3
    - name: "[Default] Using nodejs version ${{ matrix.node-version }}"
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: "[Pre] Installing dependecies"
      run: npm install
    - name: "[Running] npm run test"
      run: npm run test
