name: Node.js CI

on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: "Initializing repository"
      uses: actions/checkout@v3
    - name: "Setting up node"
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: "Installing npm packages"
      run: npm install
    - name: "Building artifacts"
      run: |
        npm run build
        # echo ::set-env name=TF_VAR_instance_label::${GITHUB_REPOSITORY#*/}-${GITHUB_SHA:0:7}
    - name: "Uploading artifacts"
      uses: actions/upload-artifact@v2
      with:
        name: "${{ github.event.repository.name }}-${{ github.sha }}"
        path: dist/app