name: Node.js CI

on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: "[Pre] Repo initialization"
      uses: actions/checkout@v3
    - name: "[Pre] Using nodejs version ${{ matrix.node-version }}"
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: "[Pre] Installing dependecies"
      run: npm install
    - name: "[Running] Building artifacts"
      run: |
        npm run build
        chmod +x dist/global-personal-data-api-linux
    - name: "[Running] Uploading artifacts"
      uses: actions/upload-artifact@v2
      with:
        name: global-personal-data-api-linux
        path: dist/global-personal-data-api-linux

