name: Node.js CI

on:
  workflow_call:
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: "[Pre] Downloading Artifacts"
        uses: actions/download-artifact@v2
        with:
          name: global-personal-data-api-linux
      - run: |
          chmod +x global-personal-data-api-linux
          ./global-personal-data-api-linux
