name: nodejs-16-build

on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: "Initializing repository"
      uses: actions/checkout@v3
    - name: "Setting up node"
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Setting up env
      run: |
        echo "GITHUB_ARTIFACT_NAME=$(echo ${GITHUB_REPOSITORY#*/}-${GITHUB_SHA:0:7})" >> $GITHUB_ENV
    - name: "Installing npm packages"
      run: npm install
    - name: "Building artifacts"
      run: |
        npm run build
        mv dist/app dist/$GITHUB_ARTIFACT_NAME
    - name: "Uploading artifacts"
      uses: actions/upload-artifact@v2
      with:
        name: "${{ env.GITHUB_ARTIFACT_NAME }}"
        path: "dist/${{ env.GITHUB_ARTIFACT_NAME }}"