name: nodejs-16-deploy

on:
  workflow_call:
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Setting up env
        run: |
          echo "GITHUB_ARTIFACT_NAME=$(echo ${GITHUB_REPOSITORY#*/}-${GITHUB_SHA:0:7})" >> $GITHUB_ENV
      - name: "Downloading Artifacts"
        uses: actions/download-artifact@v2
        with:
          name: "${{ env.GITHUB_ARTIFACT_NAME }}"
      - run: |
          ls
          # chmod +x $GITHUB_ARTIFACT_NAME
          # ./$GITHUB_ARTIFACT_NAME
